### PR TITLE
Add post: Updates to the claim declaration and confirmation pages

### PR DESCRIPTION
**Pull request by simonwhatley**

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Informing schools that the claim will be shared with providers](https://trello.com/c/9m7e0tlp/361-informing-schools-that-the-claim-will-be-shared-with-providers)

**Comment by simonwhatley** [comment]
[Update the pre-submission declaration to include grant conditions acceptance](https://trello.com/c/BPUB61n3/404-update-the-pre-submission-declaration-to-include-grant-conditions-acceptance)

**Comment by simonwhatley** [comment]
@olioldfield do ~we~ you need to include more information on why we share claim details with providers?

**Comment by simonwhatley** [comment]
[Private beta providers are informed of claims where they have been listed](https://trello.com/c/TESXfXRt/262-private-beta-providers-are-informed-of-claims-where-they-have-been-listed)

**Comment by olioldfield** [comment]
> @olioldfield do ~we~ you need to include more information on why we share claim details with providers?~

How about (please do run through grammarly etc!) :

We also updated the claim confirmation page to state that the claim will be shared with their provider. This is important as providers ensure the training is carried out. This need also arose out of a user research session with one of the early adopter providers, who expressed a wish to see claims before they had been paid. Whilst providers prior to sampling (audit) do not need to verify the claim, sharing details of the claims with them enables them to review the claims if they wish. This information may also help to prepare them for when they are asked to provide evidence to support some of the claims their placement organisations have claimed for as part of the sampling process. Sharing the claims with accredited providers prior to payment will be reviewed prior to moving to public beta, to ensure that there is a clear user need for it. If not, this process will be removed from the public beta.

**Comment by simonwhatley** [comment]
@olioldfield I have updated the post

**Review by olioldfield — APPROVED** [review]

**Pull request merged**
