### PR TITLE
Uploading bulk placements

### PR DESCRIPTION
**Pull request by andrewscrivener**
On behalf of Jennifer Dawson.

### CODE REVIEW

**Comment by JenniferDawson-shoes** [comment]
hi @andrewscrivener if there are some small amends I'd like to make, for example, adding an apostrophe to 'weve' to 'we've' then where can I make those changes?

**Comment by andrewscrivener** [comment]
Hey @JenniferDawson-shoes I've added [comments to the Trello ticket](https://trello.com/c/gLubHFJ2).
Happy to chat further if you'd like 😄

**Comment by JenniferDawson-shoes** [comment]
I want to change 2nd image to 

{{ appEmail({

subject: "Performance profile sign off for the 2022 to 2023 academic year",
content: "

And correct a typo weve to we've

**Comment by JenniferDawson-shoes** [comment]
We hadn’t imported the email macro to able to use so I’ve added
{% from "email/macro.njk" import appEmail %}
Also the build was failing due to the quotations in the email link sentence so I’ve escaped them out to fix it.
\"Performance profiles sign off\"

**Pull request merged**
