### PR TITLE
Consistent Markdown syntax

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
”How do you like to spend your evenings, @paulrobertlloyd?”

* Space after YAML frontmatter
* Descriptions end with full stop
* Use `*` for bulleted lists
* Whitespace fixes
* Fix incorrect date on one entry

### CODE REVIEW

**Comment by fofr** [comment]
Can we use `-` for bullets? It's easier to type. ¯\_(ツ)_/¯

**Comment by fofr** [comment]
Why all the full-stops added to descriptions?

**Comment by fofr** [comment]
You should write a linter 😉

**Comment by paulrobertlloyd** [comment]
> Descriptions end with full stop

Because these are sentences and, I’d image, helps when page is read aloud. (Note that there is widespread inconsistency on this across government)

> Use `*` for bulleted lists

I didn’t have a good reason until now, when reviewing entries. Where lines break just before a hyphen, the following line looks like it’s a bullet; `*` doesn’t appear in running prose (when used to embolden text, it is not surrounded by spaces).

> Space after YAML frontmatter

A concession!

> You should write a linter 😉

I actually have one set up on my own site, using [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli). I can create a PR to port that over to this site.

**Pull request merged**
