### PR TITLE
Structured data for degree qualifications (corrections)

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
* Show updated screens (https://github.com/DFE-Digital/apply-for-postgraduate-teacher-training-prototype/pull/384)
* Clarify what information is shown
* Link to HESA datasets in screenshot captions

### CODE REVIEW

**Review by fofr — APPROVED** [review]
Nice.

(Still a "destinction" typo showing in last screenshot)

**Comment by fofr** [comment]
I wonder if people might select “Unknown” before they see “I’m still studying for this degree”.

"When did you study" could come before the grade and ask if they are still studying? Then the grade screens can ask for predicted?

Currently we say "Graduation year" (https://d33wubrfki0l68.cloudfront.net/eb66d2b3822e4cffda9528d04d486f7098bc894c/f659b/images/apply-for-teacher-training/apply-launch/60-add-undergraduate-degree.png) rather than "Year graduated", as it might not be in the past.

**Comment by paulrobertlloyd** [comment]
> Currently we say "Graduation year" rather than "Year graduated", as it might not be in the past.

Odd, this flow isn’t how I remember it being designed (and testing it there are several bugs). 

Anyway, I’ve got it so that we adapt the content from ‘Year graduated’ to ‘When will you graduate?’, but maybe we needn’t do that if we use ‘Graduation year’ as a label for both scenarios?

**Comment by paulrobertlloyd** [comment]
> "When did you study" could come before the grade and ask if they are still studying? Then the grade screens can ask for predicted?

How would you ask this?

```
# When did you study?

Year started course
[        ]

Year graduated (leave blank if you haven’t completed this degree yet)
[        ]
```

or

```
# When did you study?

Have you completed this degree?

◉ Yes

  Year started course
  [        ]

  Year graduated
  [        ]

◉ No

  Year started course
  [        ]
```

**Pull request merged**
