### PR TITLE
Remove express

### PR DESCRIPTION
**Pull request by adamsilver**
Remove Express

Change build commands to work without Express both locally and in live (Netlify).

Simplify commands

`npm start` now just watches the files
`npm run watch` is for when working on the JS and CSS which is rare.

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Before we merge this, think we should at least reinstate the redirects currently in `app.js` in a Netlify config file.

I’d be tempted to not change the image paths either, and instead use rewrites for now (I *think* that’s possible). We can then remove those rewrites once we’ve reinstated image resizing using a Netlify function (which I think we should do fairly soon, as the raw images are pretty big).

**Comment by fofr** [comment]
@paulrobertlloyd This should do the trick: https://github.com/DFE-Digital/bat-design-history/pull/62

**Comment by fofr** [comment]
Any reason this branch doesn't work on Heroku? The slug size is still below 500mb.

**Comment by adamsilver** [comment]
@fofr I think because Heroku is (currently) set up to work with Express etc (buildpacks etc )

**Comment by adamsilver** [comment]
I think we're good to go. Will leave the image rewriting/resizing for another PR.

**Pull request merged**
