### PR TITLE
Adding latest Register mission patches

### PR DESCRIPTION
**Pull request by andrewscrivener**
This is a PR for updating the design history with the following Register mission patches;

- Placements 2023
- Census 2023/24
- Performance Profiles 2023/24
- Register API v1.0

### CODE REVIEW

**Comment by andrewscrivener** [comment]
A screengrab of the update is as follows;

**Comment by JenniferDawson-shoes** [comment]
Content-wise, no updates to make. The designs are amazing!

**Review by JenniferDawson-shoes — COMMENTED** [review]
Content is perfect

**Comment by andrewscrivener** [comment]
Linting failure is referring to the to the bold emphasised text on the [live post for Apply's UCD planning](https://becoming-a-teacher.design-history.education.gov.uk/apply-for-teacher-training/ucd-planning/).

Merging our branch as it's not affecting any rendering that I can see.

**Pull request merged**
