### PR TITLE
Add post: Adding multiple locations to an organisation

### PR DESCRIPTION
**Pull request by simonwhatley**

### CODE REVIEW

**Comment by simonwhatley** [comment]
[Adding locations in Support](https://trello.com/c/mN8LztJ0/1007-adding-locations-in-support)

**Comment by simonwhatley** [comment]
@Kateharries I wonder whether I separate the editing locations (view, edit and remove) part of the design history into a separate post. What do you think?

**Comment by Kateharries** [comment]
> Yes, it would make sense to put that in a separate design history so this doesn't become too long

**Review by Kateharries — APPROVED** [review]
Looks good

**Pull request merged**
