### PR TITLE
Use relative image paths

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
In preparation for simplifying figures and screenshots (see #403), update where we serve images from:

* When generating the site, copy files from the `images` folder, and save alongside post HTML. This means that, in most cases, we can continue to only call an image’s filename, but without needing to do any workarounds in the different components to get the right path
* Remove `appImage` component.
  * When used in Markdown files, use Markdown image syntax instead
  * When used in `appFigure` component, use HTML instead
* Remove `path` param on `appFigure` component, provide full path if necessary in `file` param (the `appFigure` component will be removed in a later PR)
* Update places where we reference images being in the `images` folder to point to new image locations

### CODE REVIEW

**Comment by frankieroberto** [comment]
Could we avoid the copying images step altogether, I wonder, and reference them directly from the markdown in their actual location? Perhaps even do away with the separate images folder and have an `images` subfolder of `posts/apply-for-teacher-training/`?

The copying step has thrown me a few times – and referencing them in their original location would allow GitHub markdown previews to work?  Would also avoid having to match the post slug with the images subfolder name (minus the date), which isn't intuitive.

**Comment by simonwhatley** [comment]
My preference is to have the images and markdown in the same folder for each post. 

So instead of having content in two places (`images` and `posts`):

```
/images/service-name/post-name/
  - image-01.png
  - image-02.png
  - image-03.png
/posts/service-name/
  - 2020-07-30-post-name.md
```

We would have content in one place in the `posts` folder:

```
/posts/service-name/post-name/
  - image-01.png
  - image-02.png
  - image-03.png
  - index.md
```

The latter simplifies the structure for other types of media such as documents and videos.

**Comment by frankieroberto** [comment]
> My preference is to have the images and markdown in the same folder for each post.

I like this idea too – saves having to match the folder names (which can be a pain, if you rename one).

**Comment by paulrobertlloyd** [comment]
Only downside with using folders is that posts are no longer ordered by date. But benefits are that only need to set the publish date in one place, and maybe alphabetically ordered folders are easier to use when looking for a previously published post. So, if we’re all agreed, let’s move to having posts and images together in the same folder. I’ll update this PR.

**Comment by edwardhorsford** [comment]
I'd be really keen on everything about a post in one - and using dated folders.

I've seen several cases where the date in the filename doesn't match the date in the post - would be good to clean this up.

**Comment by frankieroberto** [comment]
@edwardhorsford:

> I've seen several cases where the date in the filename doesn't match the date in the post - would be good to clean this up.

Isn’t this an argument against having dates in the folders, as it means the date is in two places? Or are you suggesting _only_ having the date in the folder?

Personally, I’m never sure what to put the date as, as it can take a few days to write and publish a post (is it meant to be publish date, or just whenever you started writing it?)

**Comment by edwardhorsford** [comment]
> @edwardhorsford:
> 
> > I've seen several cases where the date in the filename doesn't match the date in the post - would be good to clean this up.
> 
> Isn’t this an argument against having dates in the folders, as it means the date is in two places? Or are you suggesting _only_ having the date in the folder?
> 
> Personally, I’m never sure what to put the date as, as it can take a few days to write and publish a post (is it meant to be publish date, or just whenever you started writing it?)

I'm suggesting there should be only one date, wherever it is.

Personally I'd be pro publish date, but so far in register they've been backdated to when we were doing the work.

**Comment by paulrobertlloyd** [comment]
I originally tried dated folders, but was having difficulty getting 11ty to play ball. And right now, the navigation plugin is making things even more difficult. Fast falling out of love with 11ty, if I’m honest, and certainly the navigation plugin. So, so fiddly. 😡

**Comment by paulrobertlloyd** [comment]
While I agree with moving images to live in the same folders as posts, doing so is causing issues with the navigation plugin. I’m going to merge this in, create PRs for the other simplification changes, and then come back to folder reorganisation after all that’s done. (Eleventy is making me pull my hair out…)

**Pull request merged**
