### PR TITLE
User need macro

### PR DESCRIPTION
**Pull request by adamsilver**
Before:

image

After:

image

Used the style from the service manual

### CODE REVIEW

**Comment by fofr** [comment]
I think that needing to write the following:

```
{% from "user-need/macro.njk" import appUserNeed with context %}

{{appUserNeed({
  user: 'referee',
  goal: 'to provide a useful reference',
  outcome: 'I can help the candidate with their application and get back to my day as quickly as possible'
})}}
```

Instead of simply:

```
As a referee
I need to provide a useful reference
So that I can help the candidate with their application and get back to my day as quickly as possible
```

Is not the answer.

**Comment by adamsilver** [comment]
I'd love to write that to achieve the same outcome. How do we do that?

**Comment by paulrobertlloyd** [comment]
There’s always:

```html
<div class="app-user-need">
As a referee
I need to provide a useful reference
So that I can help the candidate with their application and get back to my day as quickly as possible
</div>
```

Feels icky, but works just as well.

**Comment by fofr** [comment]
Custom markdown might look like:

```
{* need *}
As a referee
I need to provide a useful reference
So that I can help the candidate with their application and get back to my day as quickly as possible
{* endneed *}
```

**Comment by adamsilver** [comment]
Put this to a vote on Slack and got the following results:

0/10 prefer option 1
7/10 prefer option 2
3/10 prefer option 3 which is a grey background and less whitespace between the paragraphs

**Pull request closed without merging**
