### PR TITLE
Add post: Financial incentives for ancient language courses

### PR DESCRIPTION
**Pull request by Kateharries**

### CODE REVIEW

**Comment by Kateharries** [comment]
[Design history on Ancient Languages](https://trello.com/c/la2GYaIQ/789-design-history-on-ancient-languages)

**Comment by frankieroberto** [comment]
Thanks for documenting this! Could you include a breakdown of which (ancient) language courses were eventually selected - I think it was all Latin and Ancient Greek?

Might be worth including some screenshots from both Publish and Find?

**Comment by frankieroberto** [comment]
Actually there are no Ancient Greek courses either - so guess they were all Latin?

**Comment by Kateharries** [comment]
[Design history on Ancient Languages](https://trello.com/c/la2GYaIQ/789-design-history-on-ancient-languages)

**Review by simonwhatley — APPROVED** [review]

**Pull request merged**
